e-venement/e-venement

- data/fixtures/30-demo.yml
fix issue #10 
Remove fields with empty value
> fix issue 10

- apps/rp/config/rpConfiguration.class.php
> (rp) set default design to tdp

- apps/rp/modules/option_csv/templates/_form_save.php
- config/e-venement.yml
- lib/form/doctrine/OptionCsvForm.class.php
This is a try for pull requests and repository merging
> I am the Master

- web/js/tck-touchscreen.js
Organisms list was not responding after #2296 patch
> (tck) Fixed a bug in the simplified selling page - refs  #2710

- apps/rp/modules/contact/templates/_show_dates.php
- lib/model/doctrine/generic/Addressable.class.php
- lib/model/doctrine/rp/Contact.class.php
- lib/model/doctrine/rp/Professional.class.php
Moved methods to the parent class
> (rp) Added creator username on the contact page - refs #2486

- apps/tck/i18n/messages.fr.xml
- apps/tck/modules/transaction/templates/_form_field_payments_list.php
- apps/tck/modules/transaction/templates/_form_field_simplified.php
- web/js/tck-touchscreen-dataloader.js
- web/js/tck-touchscreen-simplified.js
- web/js/tck-touchscreen.js
Added a label "Give change" if the "still missing" amount is negative.
Works for both standard and simplified form.
> (tck) Changed the "still missing" label in the selling form - refs #2471

- apps/event/modules/manifestation/templates/_show_spectators_list_asked.php
- apps/event/modules/manifestation/templates/_show_spectators_list_controlled.php
- apps/event/modules/manifestation/templates/_show_spectators_list_ordered.php
- apps/event/modules/manifestation/templates/_show_spectators_list_printed.php
- apps/event/modules/manifestation/templates/_show_spectators_list_tobecontrolled.php
Registered tickets should appear separately except for the buyer in a group buy of unregistered tickets
> (event) Avoid contact duplication in spectators form - refs #2703

- apps/default/i18n/menu.fr.xml
- apps/default/i18n/messages.fr.xml
- apps/default/i18n/sf_admin.fr.xml
- apps/default/modules/sellingOptions/actions/actions.class.php
- apps/default/modules/sellingOptions/config/security.yml
- apps/default/modules/sellingOptions/templates/indexSuccess.php
- apps/tck/i18n/messages.fr.xml
- apps/tck/modules/transaction/templates/_form_field_close.php
- apps/tck/modules/transaction/templates/_form_field_content_manifestations_footer.php
- apps/templates/_menu_setup_ticketting.php
- data/fixtures/10-permissions.yml
- web/js/tck-touchscreen-options.js
Added a configuration page for the selling screen in Settings/Selling menu
> (tck) - Force the input of a postal code in the selling form - refs #2561

- apps/pub/modules/manifestation/actions/actions.class.php
- apps/pub/templates/_social_networks.php
- apps/pub/templates/public.php
The title can be changed for each page
> (pub) - Social networks links share the title of the page - refs #2796

- apps/default/modules/userPolicy/actions/actions.class.php
> (default) - Changed the name of the user policy file - refs #2663

- apps/tck/modules/order/actions/actions.class.php
- apps/tck/modules/order/config/generator.yml
- lib/model/doctrine/tck/Order.class.php
> (tck) - Added a sorted option on the contact column in the Orders page - refs #1408

- apps/rp/i18n/messages.fr.xml
- apps/rp/modules/email/actions/actions.class.php
I did extensive testing and did not notice any bad behavior with file attachment or loading template.
> (rp) - Added some error messages when sending an email - refs #2785

- apps/rp/modules/contact/templates/cardSuccess.php
> (rp) - Changed the way the logo is displayed in the membercard - refs #2783

- apps/rp/modules/postalcode/actions/actions.class.php
- web/js/geo-zipcities-helper.js
> (rp) - Added a free input option to the zip code field - refs #2998

- apps/rp/modules/geo_fr_street_base/actions/actions.class.php
> (rp) - Fixed street order in the autocomplete address field of contact page - refs #2898

- apps/rp/modules/email/actions/actions.class.php
+ code refactoring
Merge to v2.10 as well.
> (rp) - Added error messages on email creation - refs #2785

- web/js/email.js
This piece of code should not have been modified. It gets the link to the newly saved email.
Merge to v2.10 as well.
> (rp) - Undo part of commit ae5cd94. It prevented adding a file to a new email - refs #3042

- web/css/tck-touchscreen-simplified.css
> (tck) Improve display simplified GUI refs#3274

- apps/pub/i18n/fr/messages.xml
> (pub) - Improve french translation - Refs#2764

- apps/museum/config/app.yml.template
> (museum) - Change app template parameter - Refs#3356

- apps/event/modules/color/templates/_form_footer.php
> (event) - Fixed a bug that prevented the color picker to work properly - refs #1980

- apps/stats/i18n/fr/messages.xml
> (stats) - Improve french translation - refs#3407

- apps/pub/i18n/br/messages.xml
> (pub) - Missing Brezhoneg translation - refs#3556

- apps/rp/i18n/messages.fr.xml
- apps/rp/modules/contact/config/generator.yml
- lib/filter/doctrine/ContactFormFilter.class.php
> (rp) - Added a filter to show only professional contacts - refs #3557

- apps/event/i18n/messages.fr.xml
- apps/pos/i18n/fr/messages.xml
- apps/rp/i18n/messages.fr.xml
- apps/srv/i18n/messages.fr.xml
- apps/stats/i18n/fr/messages.xml
- apps/tck/i18n/messages.fr.xml
> (global) - Add missing translation - refs#1258

- web/css/tck-touchscreen.css
> (tck) - improve transaction layout - refs#3725

- web/css/tck-touchscreen.css
> (tck) - improve gift coupon layout - refs#3728

- web/css/manifestation.css
> (event) - improve event CSS layout - #refs3739

- apps/default/i18n/messages.fr.xml
> (Global) - Spelling mistake in a translation - refs#3797

- apps/pub/config/app.yml.template
> (pub) - updating pub app template parameter - refs#4193

- apps/event/modules/manifestation/actions/actions.class.php
- apps/event/modules/manifestation/config/generator.yml
- apps/event/modules/manifestation/config/view.yml
- apps/event/modules/manifestation/templates/_form_files_list.php
- apps/event/modules/manifestation/templates/_form_member_cards.php
- apps/event/modules/manifestation/templates/associateMemberCardsError.php
- apps/event/modules/manifestation/templates/associateMemberCardsSuccess.php
- apps/event/modules/manifestation/templates/seatMemberCardsSuccess.php
- apps/rp/i18n/messages.fr.xml
- apps/rp/modules/contact/actions/card.php
- apps/rp/modules/contact/config/view.yml
- apps/rp/modules/contact/templates/_card_list.php
- apps/rp/modules/member_card/actions/actions.class.php
- apps/rp/modules/member_card/config/generator.yml
- apps/rp/modules/member_card/config/view.yml
- apps/rp/modules/member_card/templates/_show_privileged_seat_name.php
- apps/rp/modules/member_card/templates/setSeatSuccess.php
- config/doctrine/mc-schema.yml
- config/services.yml
- lib/form/doctrine/MemberCardPriceModelForm.class.php
- lib/service/MemberCardSeatingService.class.php
- lib/service/MemberCardsSeatingService.class.php
- lib/service/MemberCardsService.class.php
- web/css/manifestation-view.css
- web/css/rp-card.css
- web/js/rp-member-card-seat.js
> (tck) add a "stable seat" feature for a pass holder during the lifetime of its MemberCard

- web/css/rp-tdp.css
Merge as well in v2.10 / v2.11.1
> (rp) - Hide organism category field for contact - refs#4389

- web/css/kiosk/kiosk.css
Merge into master / v2.12-beta
> (kiosk) - Improve info-panel text - refs#5044

- apps/event/i18n/messages.fr.xml
> (pos) - improve translation in pos price menu - refs#5059

- apps/kiosk/config/app.yml.template
- apps/kiosk/config/extra-modules.php.template
> (kiosk) - updating config files - refs#5055

- apps/kiosk/config/app.yml.template
> Add text for cancelled order

- apps/tck/config/app.yml.template
Merge into v2.11.1 / v2.12 / v2.10
> (tck) Missing parameter in tck app.yml.template - refs#5185

- apps/kiosk/i18n/messages.fr.xml
> (kiosk) - adding translation - refs#5232

- web/css/pub-manifestation-synthetic.css
> (pub) - improve quantity input - (refs#5313)

- etc/dockerfile.jenkins
- etc/pipeline.jenkins
> [CI] Update for last CI process standard refs #5534

- apps/event/i18n/messages.fr.xml
> (EVENT) - Improve french translation - refs#5841
